CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE players (
    steam_id BIGINT PRIMARY KEY,
    level INT NOT NULL DEFAULT 1,
    experience BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);